config/routes.rb
SwinburneOnRails::Application.routes.draw do

  resources :editions

  resources :witnesses

  resources :openings

  get "pages/index", :as => :home
  get "pages/about", :as => :about
  

  root :to => 'pages#index'

end

app/models/edition.rb
class Edition < ActiveRecord::Base
  attr_accessible :author, :title, :witness_id

  belongs_to :witness
end

app/models/opening.rb
class Opening < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :running_title, :verso, :recto, :verso_page_number, :recto_page_number, :verso_notes, :recto_notes, :witness_id

  belongs_to :witness
end

app/models/witness.rb
class Witness < ActiveRecord::Base
  attr_accessible :author, :pub_place, :publisher, :title, :year, :code, :note

  has_many :openings
  has_many :editions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @editions }
    end
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
    @edition = Edition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/new
  # GET /editions/new.json
  def new
    @edition = Edition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/1/edit
  def edit
    @edition = Edition.find(params[:id])
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(params[:edition])

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render json: @edition, status: :created, location: @edition }
      else
        format.html { render action: "new" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /editions/1
  # PUT /editions/1.json
  def update
    @edition = Edition.find(params[:id])

    respond_to do |format|
      if @edition.update_attributes(params[:edition])
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition = Edition.find(params[:id])
    @edition.destroy

    respond_to do |format|
      format.html { redirect_to editions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
  # GET /openings
  # GET /openings.json
  def index
    @openings = Opening.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @openings }
    end
  end

  # GET /openings/1
  # GET /openings/1.json
  def show
    @opening = Opening.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @opening }
    end
  end

  # GET /openings/new
  # GET /openings/new.json
  def new
    @opening = Opening.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opening }
    end
  end

  # GET /openings/1/edit
  def edit
    @opening = Opening.find(params[:id])
  end

  # POST /openings
  # POST /openings.json
  def create
    @opening = Opening.new(params[:opening])

    respond_to do |format|
      if @opening.save
        format.html { redirect_to @opening, notice: 'Opening was successfully created.' }
        format.json { render json: @opening, status: :created, location: @opening }
      else
        format.html { render action: "new" }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /openings/1
  # PUT /openings/1.json
  def update
    @opening = Opening.find(params[:id])

    respond_to do |format|
      if @opening.update_attributes(params[:opening])
        format.html { redirect_to @opening, notice: 'Opening was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /openings/1
  # DELETE /openings/1.json
  def destroy
    @opening = Opening.find(params[:id])
    @opening.destroy

    respond_to do |format|
      format.html { redirect_to openings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @swinburne_edition = Edition.find_by_title('Poems and Ballads')
  end

  def about

  end
end

app/controllers/witnesses_controller.rb
class WitnessesController < ApplicationController
  # GET /witnesses
  # GET /witnesses.json
  def index
    @witnesses = Witness.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @witnesses }
    end
  end

  # GET /witnesses/1
  # GET /witnesses/1.json
  def show
    @witness = Witness.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @witness }
    end
  end

  # GET /witnesses/new
  # GET /witnesses/new.json
  def new
    @witness = Witness.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @witness }
    end
  end

  # GET /witnesses/1/edit
  def edit
    @witness = Witness.find(params[:id])
  end

  # POST /witnesses
  # POST /witnesses.json
  def create
    @witness = Witness.new(params[:witness])

    respond_to do |format|
      if @witness.save
        format.html { redirect_to @witness, notice: 'Witness was successfully created.' }
        format.json { render json: @witness, status: :created, location: @witness }
      else
        format.html { render action: "new" }
        format.json { render json: @witness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /witnesses/1
  # PUT /witnesses/1.json
  def update
    @witness = Witness.find(params[:id])

    respond_to do |format|
      if @witness.update_attributes(params[:witness])
        format.html { redirect_to @witness, notice: 'Witness was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @witness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /witnesses/1
  # DELETE /witnesses/1.json
  def destroy
    @witness = Witness.find(params[:id])
    @witness.destroy

    respond_to do |format|
      format.html { redirect_to witnesses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "Swinburne on Rails"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/witnesses_helper.rb
module WitnessesHelper
end

app/views/editions/_form.html.erb
<%= form_for(@edition) do |f| %>
  <% if @edition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
      <% @edition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editing edition</h1>

<%= render 'form' %>

<%= link_to 'Show', @edition %> |
<%= link_to 'Back', editions_path %>

app/views/editions/index.html.erb
<h1>Listing editions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @editions.each do |edition| %>
  <tr>
    <td><%= edition.title %></td>
    <td><%= edition.author %></td>
    <td><%= link_to 'Show', edition %></td>
    <td><%= link_to 'Edit', edit_edition_path(edition) %></td>
    <td><%= link_to 'Destroy', edition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Edition', new_edition_path %>

app/views/editions/new.html.erb
<h1>New edition</h1>

<%= render 'form' %>

<%= link_to 'Back', editions_path %>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @edition.title %>
</p>

<p>
  <b>Author:</b>
  <%= @edition.author %>
</p>


<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>

app/views/layouts/_flashmessages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to root_path %>
  <p>Our mission is to bring the future to critical editions</p>

  <div class="horizontal-links clearfix">
    <ul>
      <li>Editions</li>
      <li><a href="moxen">Moxen</a></li>
      <li><a href="hotten">Hotten</a></li>
    </ul>

    <ul>
      <li>Navigation</li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
     <a href="https://twitter.com/" class="twitter-link">Follow us on Twitter</a>

  </div>

 
  <div class="logo clearfix">
    <a class="waynebot-badge" href="#">
      <%= image_tag('waynebot.png') %>
    </a>
    <h2><a href="#">Built by Waynebot</a></h2>
  </div>

  <div class="copyright clearfix">
    <p>Edited with all the love in the world by <a href="https://twitter.com/nowviskie">nowviskie</a>.</p>
    <p>
    <%= link_to 'Source code', 'https://github.com/waynegraham/swinburne-on-rails' %>
    licenced under 
    <%= link_to 'Apache License v2.0', 'http://www.apache.org/licenses/LICENSE-2.0' %>.
    Content licenced under
    <%= link_to 'Creative Commons  BY-NC-SA 3.0', 'http://creativecommons.org/licenses/by-nc-sa/3.0/' %>.
    </p>
  </div>
  <footer>

app/views/layouts/_header.html.erb
<header role="banner">
  <div class="logo">
    <h1><%= link_to 'Swinburne on Rails', root_path %></h1>

  </div>
  <nav id="nav-primary">
    <ul>
      <li><%= link_to 'About' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<title><%= title %></title>
<meta name="viewport" content="width=device-width">
<link href='http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:300,400,500' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= javascript_include_tag "/js/modernizr-2.6.1.min" %>
</head>
<body>
<!--[if lt IE 7]><p class="chromeframe">Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div class="page">

<%= render 'layouts/header' %>

<div class="container">

  <%= render 'layouts/flashmessages'%>

  <div id="main" role="main">
    <%= yield %>
  </div>
</div>
 <%= render 'layouts/footer'%>
 </div>
</body>
</html>

app/views/openings/_form.html.erb
<%= form_for(@opening) do |f| %>
  <% if @opening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opening.errors.count, "error") %> prohibited this opening from being saved:</h2>

      <ul>
      <% @opening.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/openings/edit.html.erb
<h1>Editing opening</h1>

<%= render 'form' %>

<%= link_to 'Show', @opening %> |
<%= link_to 'Back', openings_path %>

app/views/openings/index.html.erb
<h1>Listing openings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @openings.each do |opening| %>
  <tr>
    <td><%= link_to 'Show', opening %></td>
    <td><%= link_to 'Edit', edit_opening_path(opening) %></td>
    <td><%= link_to 'Destroy', opening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Opening', new_opening_path %>

app/views/openings/new.html.erb
<h1>New opening</h1>

<%= render 'form' %>

<%= link_to 'Back', openings_path %>

app/views/openings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="opening">
  <div class="verso">
    <%= @opening.verso %>
  </div>
  <div class="recto">
    <%= @opening.recto %>
  </div>
</div>

<%= link_to 'Edit', edit_opening_path(@opening) %> |
<%= link_to 'Back', openings_path %>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/index.html.erb
<div class="hero-unit">

  <h1>Swinburne on Rails</h1>
  <h2>A Critical Edition for the 21st century</h2>
  <ul>
    <li class="float-up edition-box">
    <p>Critical Edition</p>
    <p>Read the edition as Swinburne intended</p>
    </li>
    <li class="apparatus-box">
    <p>Apparatus</p>
    <p>Critical apparatus.</p>
    </li>
    <li class="float-up notes-box">
    <p>Notes</p>
    <p>Notes on the work</p>
    </li>
    <li class="other-box">
    <% unless @swinburne_edition.nil? %>
      <p><%= link_to @swinburne_edition.title, @swinburne_edition %></p>
      <p>some more words</p>
    <% end %>

    </li>
  </ul>

</div>

<div class="get-started">
  <h2>Ready to see the future?</h2>
  <a href="#" class="button">Get Started</a>
</div>

app/views/witnesses/_form.html.erb
<%= form_for(@witness) do |f| %>
  <% if @witness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@witness.errors.count, "error") %> prohibited this witness from being saved:</h2>

      <ul>
      <% @witness.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :pub_place %><br />
    <%= f.text_field :pub_place %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/witnesses/edit.html.erb
<h1>Editing witness</h1>

<%= render 'form' %>

<%= link_to 'Show', @witness %> |
<%= link_to 'Back', witnesses_path %>

app/views/witnesses/index.html.erb
<h1>Listing witnesses</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Publisher</th>
    <th>Pub place</th>
    <th>Year</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @witnesses.each do |witness| %>
  <tr>
    <td><%= witness.code %></td>
    <td><%= witness.publisher %></td>
    <td><%= witness.pub_place %></td>
    <td><%= witness.year %></td>
    <td><%= witness.note %></td>
    <td><%= link_to 'Show', witness %></td>
    <td><%= link_to 'Edit', edit_witness_path(witness) %></td>
    <td><%= link_to 'Destroy', witness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Witness', new_witness_path %>

app/views/witnesses/new.html.erb
<h1>New witness</h1>

<%= render 'form' %>

<%= link_to 'Back', witnesses_path %>

app/views/witnesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @witness.title %>
</p>

<p>
  <b>Author:</b>
  <%= @witness.author %>
</p>

<p>
  <b>Publisher:</b>
  <%= @witness.publisher %>
</p>

<p>
  <b>Pub place:</b>
  <%= @witness.pub_place %>
</p>

<p>
  <b>Year:</b>
  <%= @witness.year %>
</p>


<%= link_to 'Edit', edit_witness_path(@witness) %> |
<%= link_to 'Back', witnesses_path %>